#!/usr/bin/env python3
"""Render a mods API surface JSON into a generated reference note.

Input: `mods-brain.api-surface.v1` JSON. Output: a markdown wiki note listing
every engine event, op event, classic event, `$` namespace and member, render
component, and element by surface, each with its line in the typings capture
so a claim can be checked. The hand-written [[Mods API Cheatsheet]] explains;
this generated note enumerates and is regenerated per Claude Code release.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from _render_common import clean, frontmatter, plain_footer

RELATED = [
    "Mods API Cheatsheet", "Mod Anatomy", "Hook Middleware Chain", "Mods API Namespaces", "Render Sites",
    "UI Elements and JSX", "Tool Events", "Prompt Events", "Turn and Session Events", "Agent and Command Events",
    "Versioning and API Drift", "Re-verify After Release Flow", "Classic Hook Bridge",
]


def render(surface: dict, date: str) -> str:
    version = surface["claude_code_version"]
    cite = f"types {version}"
    out = [frontmatter(
        type_="report", title=f"API Surface {version}", date=date, tested_on=version, confidence="evidence-based",
        related=RELATED,
        source_urls=[f"https://code.claude.com/docs/en/plugins/mods/reference (retrieved {date})"],
        sources=["types-" + version.replace(".", "-"), f".raw/captures/types-{version}/claude-code/index.d.ts"],
    )]
    c = surface["counts"]
    out += [
        f"# API Surface {version}",
        "",
        f"Generated from the typings Claude Code {version} wrote for a mod (`{surface['source_file']}`, "
        f"{surface['line_count']} lines, sha256 `{surface['source_sha256'][:16]}...`). It lists {c['engine_events']} engine events, "
        f"{c['op_events']} op events, {c['classic_events']} classic events, {len(surface['namespaces'])} `$` namespaces, and "
        f"{c['exported_types']} exported types. Line numbers cite the capture as `{cite} L<n>`. #confidence/evidence-based",
        "",
        "Read [[Mods API Cheatsheet]] for how to use these, [[Hook Middleware Chain]] for the hook shape, and "
        "[[Versioning and API Drift]] for why this note is regenerated after every release.",
        "",
        "## Engine events",
        "",
        "Hook these with `on(event, matcher?, hook)`. See [[Tool Events]], [[Prompt Events]], [[Turn and Session Events]], "
        "and [[Agent and Command Events]].",
        "",
        "| Event | Line | What the typings say |",
        "|---|---|---|",
    ]
    events_doc = "[docs: events](https://code.claude.com/docs/en/plugins/mods/events)"
    api_doc = "[docs: mods API](https://code.claude.com/docs/en/plugins/mods/api)"
    out += [f"| `{e['name']}` | L{e['line']} | {clean(e['summary']) or events_doc} |" for e in surface["events"]["engine"]]
    out += [
        "",
        "## Op events",
        "",
        "Every `$` method is also an event of the same name, so an earlier mod can observe or answer a later mod's call "
        "(for example `ui.close` or `fs.read`). See [[Mods API Namespaces]].",
        "",
        "| Op event | Line | What the typings say |",
        "|---|---|---|",
    ]
    out += [f"| `{e['name']}` | L{e['line']} | {clean(e['summary']) or api_doc} |" for e in surface["events"]["op"]]
    out += [
        "",
        "## Classic events",
        "",
        "Settings hook events a mod can hook as `classic.<Event>`, receiving the same stdin JSON. See [[Classic Hook Bridge]].",
        "",
        ", ".join(f"`{e}`" for e in surface["events"]["classic"]),
        "",
        "## Namespaces and members",
        "",
        "| Namespace | Line | Members |",
        "|---|---|---|",
    ]
    for ns in surface["namespaces"]:
        members = ", ".join(f"`{m['name']}` (L{m['line']})" for m in ns["members"]) or "none"
        out.append(f"| `$.{ns['name']}` | L{ns['line']} | {members} |")
    rc = surface["render_components"]
    out += [
        "",
        "## Render components",
        "",
        f"`RenderComponent` (L{rc['line']}): " + ", ".join(f"`{v}`" for v in rc["values"]) + ". See [[Render Sites]].",
        "",
        "## Elements by surface",
        "",
        "Destructure from `$.ui.resolve(e)`; there are no element globals. See [[UI Elements and JSX]].",
        "",
        "| Surface | Line | Elements |",
        "|---|---|---|",
    ]
    out += [f"| {name} | L{spec['line']} | {', '.join(spec['elements'])} |" for name, spec in surface["elements"].items()]
    out += [
        "",
        "## Caveats",
        "",
        "- Generated by `scripts/import_mod_types.py` and `scripts/render_api_cheatsheet.py`; do not edit by hand. Regenerate after a Claude Code update and diff with `scripts/diff_api_surface.py` (see [[Re-verify After Release Flow]]).",
        ("- Summaries are the first sentence of each JSDoc comment; the docs pages remain the explanation of record."
         if any(e.get("summary") for e in surface["events"]["engine"]) else
         "- This edition omits the type definitions' own wording and links each row to the official docs page; line numbers refer to the `index.d.ts` that Claude Code writes beside any mod you load."),
        "- The typings header says the surface may change between releases without notice.",
        "",
        "## Sources",
        "",
        f"- types-{version.replace('.', '-')}: `.raw/captures/types-{version}/claude-code/index.d.ts`, written by Claude Code {version}, captured {date}.",
        f"- docs-mods-reference: https://code.claude.com/docs/en/plugins/mods/reference (retrieved {date}).",
        "",
    ]
    return "\n".join(out)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--surface", required=True)
    parser.add_argument("--out", required=True)
    parser.add_argument("--date", required=True, help="ISO date stamped into the note")
    parser.add_argument("--links", choices=["wiki", "plain"], default="wiki",
                        help="plain drops wikilinks, for a standalone vault without the brain's notes")
    args = parser.parse_args(argv)
    try:
        surface = json.loads(Path(args.surface).read_text(encoding="utf-8"))
        if surface.get("schema") != "mods-brain.api-surface.v1":
            raise ValueError("not a mods-brain.api-surface.v1 file")
    except (OSError, ValueError) as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 2
    text = render(surface, args.date)
    Path(args.out).write_text(plain_footer(text, args.surface) if args.links == "plain" else text, encoding="utf-8")
    print(args.out)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
