#!/usr/bin/env python3
"""Render the synthesis JSON into a capability matrix note.

Input: `mods-brain.synthesis.v1` JSON (synthesize_mods.py). Output: a markdown
wiki note showing which events and `$` namespaces the scanned mods use, which
documented events no scanned mod uses yet (build opportunities), op events
hooked, and the verdict suggestion per mod.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from _render_common import clean, frontmatter, plain_footer

RELATED = [
    "Mod Catalog", "Ranked Build Ideas", "Mods API Namespaces", "Tool Events", "Prompt Events",
    "Turn and Session Events", "Render Sites", "Reach Levels", "Audit a Third-Party Mod Flow", "Mod Catalog",
]


def render(syn: dict, date: str) -> str:
    version = syn["claude_code_version"]
    out = [frontmatter(
        type_="report", title="Capability Matrix", date=date, tested_on=version, confidence="practitioner",
        related=RELATED,
        source_urls=[f"https://code.claude.com/docs/en/plugins/mods/reference (retrieved {date})"],
        sources=["references/data/mods-synthesis.json", "scripts/synthesize_mods.py"],
    )]
    used = {e: m for e, m in syn["event_matrix"].items() if m}
    out += [
        "# Capability Matrix",
        "",
        f"Which parts of the Claude Code {version} mods API the {syn['mods_scanned']} scanned mods actually use. "
        f"{len(used)} of {len(syn['event_matrix'])} engine events are used; {len(syn['unused_events'])} are unused, "
        "which marks where [[Ranked Build Ideas]] can still differentiate. #confidence/practitioner",
        "",
        "Scans come from `scripts/scan_mod.py` (see [[Audit a Third-Party Mod Flow]]); the catalog of community mods is "
        "[[Mod Catalog]]; audit method in [[Mod Security Audit Checklist]].",
        "",
        "## Engine events in use",
        "",
        "| Event | Used by |",
        "|---|---|",
    ]
    out += [f"| `{e}` | {', '.join(m)} |" for e, m in used.items()] or ["| none | |"]
    out += [
        "",
        "## Engine events no scanned mod uses",
        "",
        ", ".join(f"`{e}`" for e in syn["unused_events"]) or "none",
        "",
        "See [[Tool Events]], [[Prompt Events]], [[Turn and Session Events]], and [[Render Sites]] for what each enables.",
        "",
        "## Op events hooked",
        "",
    ]
    out += [f"- `{e}`: {', '.join(m)}" for e, m in syn.get("op_event_hooks", {}).items()] or ["- none"]
    out += [
        "",
        "## Namespaces in use",
        "",
        "| Namespace | Used by |",
        "|---|---|",
    ]
    out += [f"| `$.{n}` | {', '.join(m) or 'none'} |" for n, m in syn["namespace_matrix"].items()]
    out += [
        "",
        "## Verdict suggestions",
        "",
        "Suggestions come from reach and static red flags only (see [[Reach Levels]]); a human read decides.",
        "",
        "| Mod | Reach | Suggestion | Why |",
        "|---|---|---|---|",
    ]
    out += [f"| {m['name']} | {m['reach']} | {m['verdict_suggestion']} | {clean(m['verdict_reason'])} |" for m in syn["mods"]]
    if syn.get("unknown_events"):
        out += ["", "## Drift: events unknown to this surface", ""]
        out += [f"- `{e}`: {', '.join(m)}" for e, m in syn["unknown_events"].items()]
    out += [
        "",
        "## Caveats",
        "",
        "- Generated by `scripts/render_capability_matrix.py`; regenerate after new scans or a new typings capture.",
        "- Usage counts reflect only the mods scanned locally, not the whole ecosystem.",
        "",
        "## Related",
        "",
        "[[Mods API Namespaces]] explains each namespace.",
        "",
    ]
    return "\n".join(out)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--synthesis", required=True)
    parser.add_argument("--out", required=True)
    parser.add_argument("--date", required=True)
    parser.add_argument("--links", choices=["wiki", "plain"], default="wiki",
                        help="plain drops wikilinks, for a standalone vault without the brain's notes")
    args = parser.parse_args(argv)
    try:
        syn = json.loads(Path(args.synthesis).read_text(encoding="utf-8"))
        if syn.get("schema") != "mods-brain.synthesis.v1":
            raise ValueError("not a mods-brain.synthesis.v1 file")
    except (OSError, ValueError) as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 2
    text = render(syn, args.date)
    Path(args.out).write_text(plain_footer(text, args.synthesis) if args.links == "plain" else text, encoding="utf-8")
    print(args.out)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
