#!/usr/bin/env python3
"""Render one mod scan JSON into a static audit report note.

Input: a `mods-brain.mod-scan.v1` JSON (scan_mod.py). Output: a markdown wiki
note with the mod's events, `$` calls, reach level, cost surface, red flags,
and the human-read steps a static scan cannot replace. The report is evidence
for a verdict, not the verdict itself.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from _render_common import clean, frontmatter, plain_footer

RELATED = [
    "Capability Matrix", "Health Scorecard",
    "Audit a Third-Party Mod Flow", "Mod Security Audit Checklist", "Reach Levels", "Usage Cost Surface",
    "Mods Trust Model", "Prompt Injection via Mods", "Hook Middleware Chain", "Mods API Namespaces",
    "Mod Catalog", "Read Only Audit Decision",
]
SEVERITY_ORDER = {"critical": 0, "high": 1, "medium": 2, "review": 3, "info": 4}


def render(scan: dict, date: str, tested_on: str, origin: str) -> str:
    plugin = scan["plugin"]
    name = plugin["name"]
    title = f"Mod Audit {name}"
    out = [frontmatter(
        type_="report", title=title, date=date, tested_on=tested_on, confidence="practitioner",
        related=RELATED,
        source_urls=[f"https://code.claude.com/docs/en/plugins/mods/admin (retrieved {date})"],
        sources=[origin, "scripts/scan_mod.py"],
    )]
    flags = sorted(scan["red_flags"], key=lambda f: SEVERITY_ORDER.get(f["severity"], 9))
    worst = flags[0]["severity"] if flags else "none"
    out += [
        f"# {title}",
        "",
        f"Static footprint of `{name}` {plugin.get('version') or ''} ({origin}). Reach **{scan['reach']}**, "
        f"{len(scan['events'])} hooked events, {len(scan['calls'])} distinct `$` calls, worst flag: **{worst}**. "
        "A static scan reads source and never runs it; it cannot see what a `next({...e})` rewrite does or what a "
        "drawn UI says, so the human-read steps below still apply. #confidence/practitioner",
        "",
        f"Method: [[Audit a Third-Party Mod Flow]] with the [[Mod Security Audit Checklist]]. Reach follows [[Reach Levels]]; "
        f"cost follows [[Usage Cost Surface]].",
        "",
        "## Identity",
        "",
        f"- Description: {clean(plugin.get('description') or 'none')}",
        f"- Hooks module: `{scan.get('module') or 'none (not a mod)'}`",
        f"- userConfig keys: {', '.join(f'`{k}`' for k in plugin.get('user_config', [])) or 'none'}",
        f"- Classic settings hooks in the same hooks.json: {', '.join(scan.get('classic_hooks', [])) or 'none'}",
        f"- Files scanned: {len(scan['files'])} ({sum(f['lines'] for f in scan['files'])} lines)",
        "",
        "## Events hooked",
        "",
        "| Event | Matchers |",
        "|---|---|",
    ]
    out += [f"| `{e}` | {clean('; '.join(m)) or 'none (every instance)'} |" for e, m in scan["events"].items()] or ["| none | |"]
    out += [
        "",
        f"Control events (can block, rewrite, or answer): {', '.join(f'`{e}`' for e in scan.get('control_events', [])) or 'none'}. "
        "See [[Hook Middleware Chain]].",
        "",
        "## `$` calls",
        "",
        "| Call | Count |",
        "|---|---|",
    ]
    out += [f"| `$.{c}` | {n} |" for c, n in scan["calls"].items()] or ["| none | |"]
    out += [
        "",
        "## Cost surface",
        "",
    ]
    out += [f"- `{c.get('call') or c.get('event')}`: {c['why']}" for c in scan.get("cost_surface", [])] or ["- None found: no model calls, started turns, registered tools, or prompt text by static evidence."]
    out += [
        "",
        "## Red flags",
        "",
        "| Severity | Code | Detail | Files |",
        "|---|---|---|---|",
    ]
    out += [f"| {f['severity']} | `{f['code']}` | {clean(f['detail'])} | {', '.join(f['files']) or 'n/a'} |" for f in flags] or ["| none | | | |"]
    out += [
        "",
        "## Human-read steps still required",
        "",
        "1. Read every `next({...e, ...})` rewrite on `tool.call`, `prompt.*`, and `ui.render` of `ToolUse` or `AskUserQuestion`. See [[Prompt Injection via Mods]].",
        "2. Confirm what leaves the machine: every `$.http` call and its destination.",
        "3. Confirm guards fail closed: a `.catch` on each denying hook. See [[Mods Trust Model]].",
        "4. A runtime trial needs owner approval and real isolation: a separate OS user or a VM, never just a disposable project, because `$.fs` takes absolute paths. See [[Read Only Audit Decision]].",
        "",
        "## Caveats",
        "",
        f"- Generated by `scripts/render_mod_audit.py` from a scan; tested against typings {tested_on}.",
        "- Regex scanning misses aliased `$` objects and dynamic event names; treat an empty table as unproven, not clean.",
        "",
        "## Related",
        "",
        "[[Mod Catalog]] holds verdicts for community and official mods; [[Capability Matrix]] gives the static suggestion for every scanned mod, and [[Health Scorecard]] scores the owner's own mods. [[Mods API Namespaces]] explains each call.",
        "",
    ]
    return "\n".join(out)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--scan", required=True)
    parser.add_argument("--out", required=True)
    parser.add_argument("--date", required=True)
    parser.add_argument("--tested-on", required=True)
    parser.add_argument("--origin", required=True, help="where the mod came from, e.g. repo@sha (no absolute paths)")
    parser.add_argument("--links", choices=["wiki", "plain"], default="wiki",
                        help="plain drops wikilinks, for a standalone vault without the brain's notes")
    args = parser.parse_args(argv)
    try:
        scan = json.loads(Path(args.scan).read_text(encoding="utf-8"))
        if scan.get("schema") != "mods-brain.mod-scan.v1":
            raise ValueError("not a mods-brain.mod-scan.v1 file")
    except (OSError, ValueError) as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 2
    if args.origin.startswith(("/", "~")):
        print("ERROR: --origin must not be an absolute path", file=sys.stderr)
        return 2
    text = render(scan, args.date, args.tested_on, args.origin)
    Path(args.out).write_text(plain_footer(text, args.scan) if args.links == "plain" else text, encoding="utf-8")
    print(args.out)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
